server:
  port: 8081

spring:
  application:
    name: trainer-workload
  security:
    oauth2:
      resourceserver:
        jwt:
          # Fetches RSA public key from auth-server automatically
          jwk-set-uri: http://localhost:9000/oauth2/jwks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: logs/trainer-workload.log